name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: dev-icons
          deta-project: dev-icons
