name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2

      # Install Deta CLI as per docs
      # https://docs.deta.sh/docs/cli/install
      - name: Install Deta CLI
        shell: bash
        run: |
          curl -fsSL https://get.deta.dev/cli.sh | sh
      # Using the access token and existing Deta micro and project,
      # clone the micro and copy .deta metadata folder to use it in deploy
      # https://docs.deta.sh/docs/cli/commands#deta-clone
      - name: Deploy
        shell: bash
        run: |
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_TOKEN }}
          rm -rf tmp/*
          ~/.deta/bin/deta clone --name ${{ github.event.repository.name }} --project ${{ github.event.repository.name }} tmp/
          cp -r tmp/.deta .
          ~/.deta/bin/deta deploy
          ~/.deta/bin/deta auth disable
          ~/.deta/bin/deta visor disable
